package kiraju.model;
// Generated Oct 6, 2017 3:02:34 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Absensi generated by hbm2java
 */
@Entity
@Table(name="ABSENSI"
    ,schema="APP"
)
public class Absensi  implements java.io.Serializable {


     private int id;
     private Users userId;
     private Date masuk;
     private Date keluar;
     private Date total;

    public Absensi() {
    }

	
    public Absensi(int id) {
        this.id = id;
    }
    public Absensi(int id, Users userId, Date masuk, Date keluar, Date total) {
       this.id = id;
       this.userId = userId;
       this.masuk = masuk;
       this.keluar = keluar;
       this.total = total;
    }
   
    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "absensi_generator")
    @SequenceGenerator(name = "absensi_generator", sequenceName = "absensi_id", allocationSize = 1)
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="USER_ID")
    public Users getUserId() {
        return this.userId;
    }
    
    public void setUserId(Users userId) {
        this.userId = userId;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="MASUK", length=29)
    public Date getMasuk() {
        return this.masuk;
    }
    
    public void setMasuk(Date masuk) {
        this.masuk = masuk;
    }
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="KELUAR", length=29)
    public Date getKeluar() {
        return this.keluar;
    }
    
    public void setKeluar(Date keluar) {
        this.keluar = keluar;
    }
    
    @Temporal(TemporalType.TIME)
    @Column(name="TOTAL", length=8)
    public Date getTotal() {
        return this.total;
    }
    
    public void setTotal(Date total) {
        this.total = total;
    }




}


