package kiraju.model;
// Generated Oct 6, 2017 3:02:34 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Absensi generated by hbm2java
 */
public class Absensi  implements java.io.Serializable {


     private int id;
     private Users userId;
     private Date masuk;
     private Date keluar;
     private Date total;

    public Absensi() {
    }

	
    public Absensi(int id) {
        this.id = id;
    }
    public Absensi(int id, Users userId, Date masuk, Date keluar, Date total) {
       this.id = id;
       this.userId = userId;
       this.masuk = masuk;
       this.keluar = keluar;
       this.total = total;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Users getUserId() {
        return this.userId;
    }
    
    public void setUserId(Users userId) {
        this.userId = userId;
    }
    public Date getMasuk() {
        return this.masuk;
    }
    
    public void setMasuk(Date masuk) {
        this.masuk = masuk;
    }
    public Date getKeluar() {
        return this.keluar;
    }
    
    public void setKeluar(Date keluar) {
        this.keluar = keluar;
    }
    public Date getTotal() {
        return this.total;
    }
    
    public void setTotal(Date total) {
        this.total = total;
    }




}


