package kiraju.model;
// Generated May 18, 2017 12:05:47 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;




/**
 * JenisMenu generated by hbm2java
 */
@Entity
@Table(name = "jenis_menu", schema = "APP")
public class JenisMenu  implements java.io.Serializable {


     private int id;
     private String nama;
//     private Short deletedFlag;
//     private String code;
     
     //v2
     private Boolean status;

    public JenisMenu() {
    }
    
    public JenisMenu(int id) {
        this.id = id;
    }
   
    @Id
//    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "jenis_menu_generator")
    @SequenceGenerator(name = "jenis_menu_generator", sequenceName = "jenis_menu_id", allocationSize = 1)
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
//    public Short getDeletedFlag() {
//        return this.deletedFlag;
//    }
//    
//    public void setDeletedFlag(Short deletedFlag) {
//        this.deletedFlag = deletedFlag;
//    }
//
//    public String getCode() {
//        return code;
//    }
//
//    public void setCode(String code) {
//        this.code = code;
//    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }




}


