package kiraju.model;
// Generated May 18, 2017 12:05:47 PM by Hibernate Tools 4.3.1



/**
 * JenisMenu generated by hbm2java
 */
public class JenisMenu  implements java.io.Serializable {


     private int id;
     private String nama;
//     private Short deletedFlag;
//     private String code;
     
     //v2
     private Boolean status;

    public JenisMenu() {
    }
    
    public JenisMenu(int id) {
        this.id = id;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
//    public Short getDeletedFlag() {
//        return this.deletedFlag;
//    }
//    
//    public void setDeletedFlag(Short deletedFlag) {
//        this.deletedFlag = deletedFlag;
//    }
//
//    public String getCode() {
//        return code;
//    }
//
//    public void setCode(String code) {
//        this.code = code;
//    }

    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean status) {
        this.status = status;
    }




}


