package kiraju.model;
// Generated Sep 9, 2017 10:15:32 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import org.hibernate.annotations.Cascade;




/**
 * MenuItem generated by hbm2java
 */
@Entity
@Table(name="menu_item"
        ,schema="APP"
)
public class MenuItem  implements java.io.Serializable {


     private String nama;
//     private Menu menuId;
     private Integer stok;
     private String code;
     private Boolean stokFlag;
     private Integer hargaTotal;
//     private Integer modal;
//     private Integer untungCode;
//     private Integer untung;
//     private Integer tambahanCode;
//     private Integer tambahan;
     private Set<StokOpnameItem> stokOpname = new HashSet<>(0);
     
     //20171229 - kirajulite
     private JenisMenu jenisMenuId;
     private Boolean status;
     
     //20180912 - kiraju3 plus
     private Satuan satuan;
     private Set<Pesan> pesan = new HashSet<>(0);
     private Boolean isJual;
     private Set<DaftarPembelian> daftarPembelian = new HashSet<>(0);

    public MenuItem() {
    }

	
    public MenuItem(String code) {
        this.code = code;
    }
//    public MenuItem(String nama, Menu menuId, Integer stok, String code, Boolean stokFlag, Integer hargaTotal, Integer modal, Integer untungCode, Integer untung, Integer tambahanCode, Integer tambahan) {
//       this.nama = nama;
//       this.menuId = menuId;
//       this.stok = stok;
//       this.code = code;
//       this.stokFlag = stokFlag;
//       this.hargaTotal = hargaTotal;
//       this.modal = modal;
//       this.untungCode = untungCode;
//       this.untung = untung;
//       this.tambahanCode = tambahanCode;
//       this.tambahan = tambahan;
//    }
   
    @Column(name="nama", unique=true, nullable=false)
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
//    public Menu getMenuId() {
//        return this.menuId;
//    }
//    
//    public void setMenuId(Menu menuId) {
//        this.menuId = menuId;
//    }
    public Integer getStok() {
        return this.stok;
    }
    
    public void setStok(Integer stok) {
        this.stok = stok;
    }
    
    @Id
    @Column(name="code", nullable=false)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    @Column(name="stok_flag", nullable=false)
    public Boolean getStokFlag() {
        return this.stokFlag;
    }
    
    public void setStokFlag(Boolean stokFlag) {
        this.stokFlag = stokFlag;
    }
    
    @Column(name="harga_total")
    public Integer getHargaTotal() {
        return this.hargaTotal;
    }
    
    public void setHargaTotal(Integer hargaTotal) {
        this.hargaTotal = hargaTotal;
    }
//    public Integer getModal() {
//        return this.modal;
//    }
//    
//    public void setModal(Integer modal) {
//        this.modal = modal;
//    }
//    public Integer getUntungCode() {
//        return this.untungCode;
//    }
//    
//    public void setUntungCode(Integer untungCode) {
//        this.untungCode = untungCode;
//    }
//    public Integer getUntung() {
//        return this.untung;
//    }
//    
//    public void setUntung(Integer untung) {
//        this.untung = untung;
//    }
//    public Integer getTambahanCode() {
//        return this.tambahanCode;
//    }
//    
//    public void setTambahanCode(Integer tambahanCode) {
//        this.tambahanCode = tambahanCode;
//    }
//    public Integer getTambahan() {
//        return this.tambahan;
//    }
//    
//    public void setTambahan(Integer tambahan) {
//        this.tambahan = tambahan;
//    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="menuItemCode")
    public Set<StokOpnameItem> getStokOpname() {
        return stokOpname;
    }

    public void setStokOpname(Set<StokOpnameItem> stokOpname) {
        this.stokOpname = stokOpname;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="jenis_menu_id", nullable=false)
    public JenisMenu getJenisMenuId() {
        return jenisMenuId;
    }

    public void setJenisMenuId(JenisMenu jenisMenuId) {
        this.jenisMenuId = jenisMenuId;
    }

    @Column(name="status", nullable=false)
    public Boolean getStatus() {
        return status;
    }

    public void setStatus(Boolean Status) {
        this.status = Status;
    }

    @ManyToOne
    @JoinColumn(name = "satuan")
    public Satuan getSatuan() {
        return satuan;
    }

    public void setSatuan(Satuan satuan) {
        this.satuan = satuan;
    }

    @OneToMany(cascade=CascadeType.REMOVE, fetch=FetchType.LAZY, mappedBy="menuItemCode")
    @Cascade( {org.hibernate.annotations.CascadeType.DELETE_ORPHAN} )
    public Set<Pesan> getPesan() {
        return pesan;
    }

    public void setPesan(Set<Pesan> pesan) {
        this.pesan = pesan;
    }

    @Column(name="is_jual", nullable=false)
    public Boolean getIsJual() {
        return isJual;
    }

    public void setIsJual(Boolean isJual) {
        this.isJual = isJual;
    }

    @OneToMany(cascade=CascadeType.REMOVE, fetch=FetchType.LAZY, mappedBy="menuItemCd")
    @Cascade( {org.hibernate.annotations.CascadeType.DELETE_ORPHAN} )
    public Set<DaftarPembelian> getDaftarPembelian() {
        return daftarPembelian;
    }

    public void setDaftarPembelian(Set<DaftarPembelian> daftarPembelian) {
        this.daftarPembelian = daftarPembelian;
    }




}


