package kiraju.model;
// Generated Oct 3, 2017 10:59:09 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;




/**
 * MetodePembayaran generated by hbm2java
 */
@Entity
@Table(name = "metode_pembayaran", schema = "APP")
public class MetodePembayaran  implements java.io.Serializable {


     private int id;
     private String nama;
     private Boolean status;

    public MetodePembayaran() {
    }

	
    public MetodePembayaran(int id) {
        this.id = id;
    }
    public MetodePembayaran(int id, String nama, Boolean status) {
       this.id = id;
       this.nama = nama;
       this.status = status;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "metode_pembayaran_generator")
//    @SequenceGenerator(name = "metode_pembayaran_generator", sequenceName = "metode_pembayaran_id")
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


