package kiraju.model;
// Generated Sep 27, 2017 5:09:04 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;




/**
 * Pajak generated by hbm2java
 */
@Entity
@Table(name = "pajak", schema = "APP")
public class Pajak  implements java.io.Serializable {


     private int id;
     private String nama;
     private Integer tipe;
     private Integer bilangan;
     private Boolean status;

    public Pajak() {
    }

	
    public Pajak(int id) {
        this.id = id;
    }
    public Pajak(int id, String nama, Integer tipe, Integer bilangan, Boolean status) {
       this.id = id;
       this.nama = nama;
       this.tipe = tipe;
       this.bilangan = bilangan;
       this.status = status;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "pajak_generator")
    @SequenceGenerator(name = "pajak_generator", sequenceName = "pajak_id")
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Integer getTipe() {
        return this.tipe;
    }
    
    public void setTipe(Integer tipe) {
        this.tipe = tipe;
    }
    public Integer getBilangan() {
        return this.bilangan;
    }
    
    public void setBilangan(Integer bilangan) {
        this.bilangan = bilangan;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }




}


