package kiraju.model;
// Generated Oct 5, 2017 3:24:32 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pelanggan generated by hbm2java
 */
public class Pelanggan  implements java.io.Serializable {


     private String id;
     private String nama;
     private String alamat;
     private String noTelp;
     private Boolean status;
     private Date dtStart;

    public Pelanggan() {
    }

	
    public Pelanggan(String id) {
        this.id = id;
    }
    public Pelanggan(String id, String nama, String alamat, String noTelp, Boolean status, Date dtStart) {
       this.id = id;
       this.nama = nama;
       this.alamat = alamat;
       this.noTelp = noTelp;
       this.status = status;
       this.dtStart = dtStart;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getNoTelp() {
        return this.noTelp;
    }
    
    public void setNoTelp(String noTelp) {
        this.noTelp = noTelp;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Date getDtStart() {
        return this.dtStart;
    }
    
    public void setDtStart(Date dtStart) {
        this.dtStart = dtStart;
    }




}


