package kiraju.model;
// Generated May 18, 2017 12:05:47 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pengeluaran generated by hbm2java
 */
public class Pengeluaran  implements java.io.Serializable {


     private int id;
     private String nama;
     private Integer harga;
     private Date dtOnly;

    public Pengeluaran() {
    }

	
    public Pengeluaran(int id) {
        this.id = id;
    }
    public Pengeluaran(int id, String nama, Integer harga, Date dtOnly) {
       this.id = id;
       this.nama = nama;
       this.harga = harga;
       this.dtOnly = dtOnly;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Integer getHarga() {
        return this.harga;
    }
    
    public void setHarga(Integer harga) {
        this.harga = harga;
    }
    public Date getDtOnly() {
        return this.dtOnly;
    }
    
    public void setDtOnly(Date dtOnly) {
        this.dtOnly = dtOnly;
    }




}


