package kiraju.model;
// Generated May 18, 2017 12:05:47 PM by Hibernate Tools 4.3.1



/**
 * Pesan generated by hbm2java
 */
public class Pesan  implements java.io.Serializable {


     private int id;
     private Transaksi transaksiId;
     private Integer jumlah;
//     private Integer modal;
//     private Integer untung;
//     private Integer tambahan;
     private MenuItem menuItemCode;
     
     //20171222 - kiraju3
     private Integer harga;

    public Pesan() {
    }

	
    public Pesan(Transaksi transaksiId) {
        this.transaksiId = transaksiId;
    }
    public Pesan(Transaksi transaksiId, Integer jumlah) {
       this.transaksiId = transaksiId;
       this.jumlah = jumlah;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Transaksi getTransaksiId() {
        return this.transaksiId;
    }
    
    public void setTransaksiId(Transaksi transaksiId) {
        this.transaksiId = transaksiId;
    }
    
    public Integer getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(Integer jumlah) {
        this.jumlah = jumlah;
    }

//    public Integer getModal() {
//        return modal;
//    }
//
//    public void setModal(Integer modal) {
//        this.modal = modal;
//    }
//
//    public Integer getUntung() {
//        return untung;
//    }
//
//    public void setUntung(Integer untung) {
//        this.untung = untung;
//    }
//
//    public Integer getTambahan() {
//        return tambahan;
//    }
//
//    public void setTambahan(Integer tambahan) {
//        this.tambahan = tambahan;
//    }

    public MenuItem getMenuItemCode() {
        return menuItemCode;
    }

    public void setMenuItemCode(MenuItem menuItemCode) {
        this.menuItemCode = menuItemCode;
    }

    public Integer getHarga() {
        return harga;
    }

    public void setHarga(Integer harga) {
        this.harga = harga;
    }




}


