package kiraju.model;
// Generated May 18, 2017 12:05:47 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Posisi generated by hbm2java
 */
@Entity
@Table(name = "posisi", schema = "APP")
public class Posisi  implements java.io.Serializable {


     private int id;
     private String nama;

    public Posisi() {
    }

	
    public Posisi(int id) {
        this.id = id;
    }
    public Posisi(int id, String nama) {
       this.id = id;
       this.nama = nama;
    }
   
    @Id
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }




}


