package kiraju.model;
// Generated May 18, 2017 12:05:47 PM by Hibernate Tools 4.3.1



/**
 * Posisi generated by hbm2java
 */
public class Posisi  implements java.io.Serializable {


     private int id;
     private String nama;

    public Posisi() {
    }

	
    public Posisi(int id) {
        this.id = id;
    }
    public Posisi(int id, String nama) {
       this.id = id;
       this.nama = nama;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }




}


