package kiraju.model;
// Generated Sep 12, 2018 10:30:30 AM by Hibernate Tools 4.3.1



/**
 * Satuan generated by hbm2java
 */
public class Satuan  implements java.io.Serializable {


     private String code;
     private String nama;

    public Satuan() {
    }

	
    public Satuan(String code) {
        this.code = code;
    }
    public Satuan(String code, String nama) {
       this.code = code;
       this.nama = nama;
    }
   
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }




}


