package kiraju.model;
// Generated Sep 12, 2018 10:30:30 AM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;




/**
 * Satuan generated by hbm2java
 */
@Entity
@Table(name="satuan", schema = "APP")
public class Satuan  implements java.io.Serializable {


     private String code;
     private String nama;

    public Satuan() {
    }

    
    public Satuan(String code) {
        this.code = code;
    }
    public Satuan(String code, String nama) {
       this.code = code;
       this.nama = nama;
    }
   
    @Id
    @Column(name="code", nullable=false)
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }




}


