package kiraju.model;
// Generated Sep 22, 2017 2:46:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StokOpname generated by hbm2java
 */
@Entity
@Table(name="stok_opname", schema = "APP")
public class StokOpname  implements java.io.Serializable {


     private int id;
     private Date tanggal;
     private String nama;
     private Boolean status;
     private Users userId;
     private Set<StokOpnameItem> stokOpnameItem = new HashSet<>(0);

    public StokOpname() {
    }

	
    public StokOpname(int id) {
        this.id = id;
    }
    public StokOpname(int id, Date tanggal, String nama, Boolean status, Users userId) {
       this.id = id;
       this.tanggal = tanggal;
       this.nama = nama;
       this.status = status;
       this.userId = userId;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
//    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "stok_opname_generator")
    @SequenceGenerator(name = "stok_opname_generator", sequenceName = "stok_opname_id")
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="tanggal")
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="user_id")
    public Users getUserId() {
        return this.userId;
    }
    
    public void setUserId(Users userId) {
        this.userId = userId;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="stokOpnameId")
    public Set<StokOpnameItem> getStokOpnameItem() {
        return stokOpnameItem;
    }

    public void setStokOpnameItem(Set<StokOpnameItem> stokOpnameItem) {
        this.stokOpnameItem = stokOpnameItem;
    }




}


