package kiraju.model;
// Generated Sep 22, 2017 2:46:46 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * StokOpname generated by hbm2java
 */
public class StokOpname  implements java.io.Serializable {


     private int id;
     private Date tanggal;
     private String nama;
     private Boolean status;
     private Users userId;
     private Set<StokOpnameItem> stokOpnameItem = new HashSet<>(0);

    public StokOpname() {
    }

	
    public StokOpname(int id) {
        this.id = id;
    }
    public StokOpname(int id, Date tanggal, String nama, Boolean status, Users userId) {
       this.id = id;
       this.tanggal = tanggal;
       this.nama = nama;
       this.status = status;
       this.userId = userId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }
    public Users getUserId() {
        return this.userId;
    }
    
    public void setUserId(Users userId) {
        this.userId = userId;
    }

    public Set<StokOpnameItem> getStokOpnameItem() {
        return stokOpnameItem;
    }

    public void setStokOpnameItem(Set<StokOpnameItem> stokOpnameItem) {
        this.stokOpnameItem = stokOpnameItem;
    }




}


