package kiraju.model;
// Generated Sep 22, 2017 2:46:46 PM by Hibernate Tools 4.3.1



/**
 * StokOpnameItem generated by hbm2java
 */
public class StokOpnameItem  implements java.io.Serializable {


     private int id;
     private StokOpname stokOpnameId;
//     private MenuItem menuItemId;
     private Integer stokTersedia;
     private Integer stokSelisih;
     private Integer stokAwal;
     private MenuItem menuItemCode;
     private String ket;

    public StokOpnameItem() {
    }

	
    public StokOpnameItem(int id) {
        this.id = id;
    }
    public StokOpnameItem(int id, StokOpname stokOpnameId) {
       this.id = id;
       this.stokOpnameId = stokOpnameId;
//       this.menuItemId = menuItemId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public StokOpname getStokOpnameId() {
        return this.stokOpnameId;
    }
    
    public void setStokOpnameId(StokOpname stokOpnameId) {
        this.stokOpnameId = stokOpnameId;
    }
//    public MenuItem getMenuItemId() {
//        return this.menuItemId;
//    }
//    
//    public void setMenuItemId(MenuItem menuItemId) {
//        this.menuItemId = menuItemId;
//    }

    public Integer getStokTersedia() {
        return stokTersedia;
    }

    public void setStokTersedia(Integer stokTersedia) {
        this.stokTersedia = stokTersedia;
    }

    public Integer getStokSelisih() {
        return stokSelisih;
    }

    public void setStokSelisih(Integer stokSelisih) {
        this.stokSelisih = stokSelisih;
    }

    public Integer getStokAwal() {
        return stokAwal;
    }

    public void setStokAwal(Integer stokAwal) {
        this.stokAwal = stokAwal;
    }

    public MenuItem getMenuItemCode() {
        return menuItemCode;
    }

    public void setMenuItemCode(MenuItem menuItemCode) {
        this.menuItemCode = menuItemCode;
    }

    public String getKet() {
        return ket;
    }

    public void setKet(String ket) {
        this.ket = ket;
    }




}


