package kiraju.model;
// Generated Sep 12, 2018 12:36:22 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TransaksiPembelian generated by hbm2java
 */
@Entity
@Table(name="transaksi_pembelian"
        ,schema="APP"
)
public class TransaksiPembelian  implements java.io.Serializable {


     private int id;
     private Date tanggal;
     private Integer total;
     private Pemasok pemasokId;
//     private MetodePembayaran mtdByrId;
//     private Boolean isLunas;
     private Boolean status;
     private Set<DaftarPembelian> daftarPembelian = new HashSet<>(0);

    public TransaksiPembelian() {
    }

	
    public TransaksiPembelian(int id) {
        this.id = id;
    }
    public TransaksiPembelian(int id, Date tanggal, Integer total, Pemasok pemasokId, Boolean status) {
       this.id = id;
       this.tanggal = tanggal;
       this.total = total;
       this.pemasokId = pemasokId;
//       this.mtdByrId = mtdByrId;
//       this.isLunas = isLunas;
       this.status = status;
    }
   
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "transaksi_pembelian_generator")
    @SequenceGenerator(name = "transaksi_pembelian_generator", sequenceName = "transaksi_pembelian_id")
    @Column(name="id", nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Temporal(TemporalType.DATE)
    @Column(name="tanggal")
    public Date getTanggal() {
        return this.tanggal;
    }
    
    public void setTanggal(Date tanggal) {
        this.tanggal = tanggal;
    }
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }
    
    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="pemasok_id")
    public Pemasok getPemasokId() {
        return this.pemasokId;
    }
    
    public void setPemasokId(Pemasok pemasokId) {
        this.pemasokId = pemasokId;
    }
//    public MetodePembayaran getMtdByrId() {
//        return this.mtdByrId;
//    }
//    
//    public void setMtdByrId(MetodePembayaran mtdByrId) {
//        this.mtdByrId = mtdByrId;
//    }
//    public Boolean getIsLunas() {
//        return this.isLunas;
//    }
//    
//    public void setIsLunas(Boolean isLunas) {
//        this.isLunas = isLunas;
//    }
    public Boolean getStatus() {
        return this.status;
    }
    
    public void setStatus(Boolean status) {
        this.status = status;
    }

    @OneToMany(mappedBy="trxPembelianId", cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    public Set<DaftarPembelian> getDaftarPembelian() {
        return daftarPembelian;
    }

    public void setDaftarPembelian(Set<DaftarPembelian> daftarPembelian) {
        this.daftarPembelian = daftarPembelian;
    }




}


