package kiraju.model;
// Generated Oct 10, 2018 2:07:14 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Umum generated by hbm2java
 */
@Entity
@Table(name="UMUM"
    ,schema="APP"
)
public class Umum  implements java.io.Serializable {


     private short id;
     private Date installDt;
     private Boolean modeCafe;
     private String printerCode;

    public Umum() {
    }

	
    public Umum(short id) {
        this.id = id;
    }
    public Umum(short id, Date installDt, Boolean modeCafe, String printerCode) {
       this.id = id;
       this.installDt = installDt;
       this.modeCafe = modeCafe;
       this.printerCode = printerCode;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false)
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="INSTALL_DT", length=10)
    public Date getInstallDt() {
        return this.installDt;
    }
    
    public void setInstallDt(Date installDt) {
        this.installDt = installDt;
    }

    
    @Column(name="MODE_CAFE")
    public Boolean getModeCafe() {
        return this.modeCafe;
    }
    
    public void setModeCafe(Boolean modeCafe) {
        this.modeCafe = modeCafe;
    }

    
    @Column(name="PRINTER_CODE", length=20)
    public String getPrinterCode() {
        return this.printerCode;
    }
    
    public void setPrinterCode(String printerCode) {
        this.printerCode = printerCode;
    }




}


