-- ============================

-- This file was created using Derby's dblook utility.
-- Timestamp: 2017-10-18 22:15:46.746
-- Source database is: kiraju
-- Connection URL is: jdbc:derby://localhost:1527/kiraju; user=app;password=password
-- appendLogs: false

-- ----------------------------------------------
-- DDL Statements for tables
-- ----------------------------------------------

CREATE TABLE "APP"."TRANSAKSI" ("ID" INTEGER NOT NULL, "MEJA_ID" SMALLINT, "DT_START" TIMESTAMP, "DT_END" TIMESTAMP, "STATUS" SMALLINT, "NAMA_PEMESAN" VARCHAR(20), "END_DT_ONLY" DATE, "END_TIME_ONLY" TIME, "TOTAL" INTEGER, "METODE_PEMBAYARAN_ID" SMALLINT, "DISKON_ID" INTEGER, "PAJAK_ID" INTEGER, "DISKON_TOTAL" INTEGER, "PAJAK_TOTAL" INTEGER, "PELANGGAN_ID" VARCHAR(50), "USER_START" VARCHAR(20), "USER_END" VARCHAR(20), "MODAL_TOTAL" INTEGER);

CREATE TABLE "APP"."JENIS_MENU" ("ID" INTEGER NOT NULL, "NAMA" VARCHAR(50), "STATUS" BOOLEAN);

CREATE TABLE "APP"."MENU" ("ID" INTEGER NOT NULL, "NAMA" VARCHAR(50), "CREATED_DT" TIMESTAMP, "UPDATED_DT" TIMESTAMP, "STATUS" BOOLEAN, "JENIS_MENU_ID" INTEGER);

CREATE TABLE "APP"."PAJAK" ("ID" INTEGER NOT NULL, "NAMA" VARCHAR(50), "TIPE" INTEGER, "BILANGAN" INTEGER, "STATUS" BOOLEAN);

CREATE TABLE "APP"."GENERAL" ("INSTALL_DT" DATE);

CREATE TABLE "APP"."STOK_OPNAME" ("ID" INTEGER NOT NULL, "TANGGAL" DATE, "NAMA" VARCHAR(100), "STATUS" BOOLEAN, "USER_ID" VARCHAR(20));

CREATE TABLE "APP"."USERS" ("ID" VARCHAR(20) NOT NULL, "NAMA" VARCHAR(50) NOT NULL, "USERNAME" VARCHAR(20) NOT NULL, "PASSWORD" VARCHAR(20) NOT NULL, "POSISI_ID" INTEGER NOT NULL, "STATUS" BOOLEAN NOT NULL, "STATUS_ABSENSI" BOOLEAN NOT NULL);

CREATE TABLE "APP"."ABSENSI" ("ID" INTEGER NOT NULL, "MASUK" TIMESTAMP, "KELUAR" TIMESTAMP, "TOTAL" TIME, "USER_ID" VARCHAR(20));

CREATE TABLE "APP"."STOK_OPNAME_ITEM" ("ID" INTEGER NOT NULL, "STOK_OPNAME_ID" INTEGER, "STOK_TERSEDIA" INTEGER, "STOK_SELISIH" INTEGER, "STOK_AWAL" INTEGER, "MENU_ITEM_CODE" VARCHAR(20), "KET" VARCHAR(250));

CREATE TABLE "APP"."POSISI" ("ID" INTEGER NOT NULL, "NAMA" VARCHAR(20));

CREATE TABLE "APP"."PESAN" ("ID" INTEGER NOT NULL, "TRANSAKSI_ID" INTEGER, "JUMLAH" INTEGER, "MODAL" INTEGER, "UNTUNG" INTEGER, "TAMBAHAN" INTEGER, "MENU_ITEM_CODE" VARCHAR(20));

CREATE TABLE "APP"."DISKON" ("ID" INTEGER NOT NULL, "TIPE" INTEGER, "BILANGAN" INTEGER, "STATUS" BOOLEAN, "NAMA" VARCHAR(50));

CREATE TABLE "APP"."PELANGGAN" ("ID" VARCHAR(50) NOT NULL, "NAMA" VARCHAR(100), "ALAMAT" VARCHAR(250), "NO_TELP" VARCHAR(20), "STATUS" BOOLEAN, "DT_START" TIMESTAMP);

CREATE TABLE "APP"."MENU_ITEM" ("CODE" VARCHAR(20) NOT NULL, "NAMA" VARCHAR(50), "MODAL" INTEGER, "UNTUNG_CODE" INTEGER, "UNTUNG" INTEGER, "TAMBAHAN_CODE" INTEGER, "TAMBAHAN" INTEGER, "HARGA_TOTAL" INTEGER, "MENU_ID" INTEGER, "STOK" INTEGER, "STOK_FLAG" BOOLEAN);

CREATE TABLE "APP"."METODE_PEMBAYARAN" ("ID" INTEGER NOT NULL, "NAMA" VARCHAR(50), "STATUS" BOOLEAN);

CREATE TABLE "APP"."PENGELUARAN" ("ID" INTEGER NOT NULL, "NAMA" VARCHAR(100), "HARGA" INTEGER, "DT_ONLY" DATE);

CREATE TABLE "APP"."MEJA" ("ID" SMALLINT NOT NULL, "STATUS" SMALLINT, "NOMOR" VARCHAR(10));

-- ----------------------------------------------
-- DDL Statements for keys
-- ----------------------------------------------

-- PRIMARY/UNIQUE
ALTER TABLE "APP"."TRANSAKSI" ADD CONSTRAINT "TRX_PK" PRIMARY KEY ("ID");

ALTER TABLE "APP"."STOK_OPNAME" ADD CONSTRAINT "SQL170922142105860" PRIMARY KEY ("ID");

ALTER TABLE "APP"."DISKON" ADD CONSTRAINT "SQL170927170435120" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENU" ADD CONSTRAINT "MN_PK" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENU" ADD CONSTRAINT "MN_U_NAMA" UNIQUE ("NAMA");

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "SQL171017231307870" PRIMARY KEY ("ID");

ALTER TABLE "APP"."USERS" ADD CONSTRAINT "USR_U_USERNAME" UNIQUE ("USERNAME");

ALTER TABLE "APP"."MEJA" ADD CONSTRAINT "MJ_PK" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MEJA" ADD CONSTRAINT "MJ_U_NOMOR" UNIQUE ("NOMOR");

ALTER TABLE "APP"."POSISI" ADD CONSTRAINT "SQL171017224342480" PRIMARY KEY ("ID");

ALTER TABLE "APP"."ABSENSI" ADD CONSTRAINT "SQL170913182046470" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PESAN" ADD CONSTRAINT "PSN_PK" PRIMARY KEY ("ID");

ALTER TABLE "APP"."PAJAK" ADD CONSTRAINT "SQL170927170656720" PRIMARY KEY ("ID");

ALTER TABLE "APP"."METODE_PEMBAYARAN" ADD CONSTRAINT "SQL171003105649120" PRIMARY KEY ("ID");

ALTER TABLE "APP"."STOK_OPNAME_ITEM" ADD CONSTRAINT "SQL170922142243840" PRIMARY KEY ("ID");

ALTER TABLE "APP"."MENU_ITEM" ADD CONSTRAINT "SQL171015102232660" PRIMARY KEY ("CODE");

ALTER TABLE "APP"."PENGELUARAN" ADD CONSTRAINT "KLR_PK" PRIMARY KEY ("ID");

ALTER TABLE "APP"."JENIS_MENU" ADD CONSTRAINT "SQL171017175900690" PRIMARY KEY ("ID");

ALTER TABLE "APP"."JENIS_MENU" ADD CONSTRAINT "JM_U_NAMA" UNIQUE ("NAMA");

ALTER TABLE "APP"."PELANGGAN" ADD CONSTRAINT "SQL171005132629320" PRIMARY KEY ("ID");

-- FOREIGN
ALTER TABLE "APP"."TRANSAKSI" ADD CONSTRAINT "FK_MEJA" FOREIGN KEY ("MEJA_ID") REFERENCES "APP"."MEJA" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSAKSI" ADD CONSTRAINT "FK_PELANGGAN" FOREIGN KEY ("PELANGGAN_ID") REFERENCES "APP"."PELANGGAN" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSAKSI" ADD CONSTRAINT "FK_T_USER_START" FOREIGN KEY ("USER_START") REFERENCES "APP"."USERS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."TRANSAKSI" ADD CONSTRAINT "FK_T_USER_END" FOREIGN KEY ("USER_END") REFERENCES "APP"."USERS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."STOK_OPNAME" ADD CONSTRAINT "FK_SO_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "APP"."USERS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."MENU" ADD CONSTRAINT "FK_JENIS_MENU" FOREIGN KEY ("JENIS_MENU_ID") REFERENCES "APP"."JENIS_MENU" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."ABSENSI" ADD CONSTRAINT "FK_A_USER_ID" FOREIGN KEY ("USER_ID") REFERENCES "APP"."USERS" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PESAN" ADD CONSTRAINT "FK_TRANSAKSI" FOREIGN KEY ("TRANSAKSI_ID") REFERENCES "APP"."TRANSAKSI" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."PESAN" ADD CONSTRAINT "FK_MENU_ITEM" FOREIGN KEY ("MENU_ITEM_CODE") REFERENCES "APP"."MENU_ITEM" ("CODE") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."STOK_OPNAME_ITEM" ADD CONSTRAINT "FK_STOK_OPNAME_ID" FOREIGN KEY ("STOK_OPNAME_ID") REFERENCES "APP"."STOK_OPNAME" ("ID") ON DELETE NO ACTION ON UPDATE NO ACTION;

ALTER TABLE "APP"."STOK_OPNAME_ITEM" ADD CONSTRAINT "FK_SOI_MENU_ITEM" FOREIGN KEY ("MENU_ITEM_CODE") REFERENCES "APP"."MENU_ITEM" ("CODE") ON DELETE NO ACTION ON UPDATE NO ACTION;


---------------------------
-- DML STATEMENT FOR POSISI
---------------------------
INSERT INTO APP.POSISI (ID, NAMA) 
	VALUES (1, 'Hidden User');
INSERT INTO APP.POSISI (ID, NAMA) 
	VALUES (2, 'Super User');
INSERT INTO APP.POSISI (ID, NAMA) 
	VALUES (3, 'Tanpa User');
INSERT INTO APP.POSISI (ID, NAMA) 
	VALUES (4, 'Administrator');
INSERT INTO APP.POSISI (ID, NAMA) 
	VALUES (5, 'Kasir');
INSERT INTO APP.POSISI (ID, NAMA) 
	VALUES (6, 'Staf');

---------------------------
-- DML STATEMENT FOR USERS
---------------------------
INSERT INTO APP.USERS (ID, NAMA, USERNAME, PASSWORD, POSISI_ID, STATUS, STATUS_ABSENSI) 
	VALUES ('1', 'Hidden User', 'sondok', 'p@ssw0rd123', 1, true, false);
INSERT INTO APP.USERS (ID, NAMA, USERNAME, PASSWORD, POSISI_ID, STATUS, STATUS_ABSENSI) 
	VALUES ('2', 'Super User', 'su', 'password', 2, true, false);
INSERT INTO APP.USERS (ID, NAMA, USERNAME, PASSWORD, POSISI_ID, STATUS, STATUS_ABSENSI) 
	VALUES ('3', 'Tanpa User', 'kiraju', 'password', 3, true, false);
INSERT INTO APP.USERS (ID, NAMA, USERNAME, PASSWORD, POSISI_ID, STATUS, STATUS_ABSENSI) 
	VALUES ('4', 'Admin', 'adm', 'password', 4, true, false);
INSERT INTO APP.USERS (ID, NAMA, USERNAME, PASSWORD, POSISI_ID, STATUS, STATUS_ABSENSI) 
	VALUES ('5', 'Kasir', 'ksr', 'password', 5, true, false);
INSERT INTO APP.USERS (ID, NAMA, USERNAME, PASSWORD, POSISI_ID, STATUS, STATUS_ABSENSI) 
	VALUES ('6', 'Staf', 'stf', 'password', 6, true, false);

---------------------------
-- DML STATEMENT FOR METODE PEMBAYARAN
---------------------------
INSERT INTO APP.METODE_PEMBAYARAN (ID, NAMA, STATUS) 
	VALUES (1, 'Tunai', true);


---------------------------
-- DML STATEMENT FOR MEJA
---------------------------
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (0, 1, '0');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (1, 0, '1');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (2, 0, '2');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (3, 0, '3');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (4, 0, '4');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (5, 0, '5');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (6, 0, '6');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (7, 0, '7');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (8, 0, '8');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (9, 0, '9');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (10, 0, '10');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (11, 0, '11');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (12, 0, '12');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (13, 0, '13');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (14, 0, '14');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (15, 0, '15');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (16, 0, '16');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (17, 0, '17');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (18, 0, '18');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (19, 0, '19');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (20, 0, '20');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (21, 0, '21');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (22, 0, '22');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (23, 0, '23');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (24, 0, '24');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (25, 0, '25');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (26, 0, '26');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (27, 0, '27');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (28, 0, '28');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (29, 0, '29');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (30, 0, '30');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (31, 0, '31');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (32, 0, '32');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (33, 0, '33');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (34, 0, '34');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (35, 0, '35');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (36, 0, '36');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (37, 0, '37');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (38, 0, '38');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (39, 0, '39');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (40, 0, '40');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (41, 0, '41');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (42, 0, '42');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (43, 0, '43');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (44, 0, '44');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (45, 0, '45');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (46, 0, '46');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (47, 0, '47');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (48, 0, '48');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (49, 0, '49');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (50, 0, '50');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (51, 0, '51');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (52, 0, '52');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (53, 0, '53');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (54, 0, '54');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (55, 0, '55');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (56, 0, '56');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (57, 0, '57');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (58, 0, '58');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (59, 0, '59');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (60, 0, '60');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (61, 0, '61');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (62, 0, '62');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (63, 0, '63');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (64, 0, '64');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (65, 0, '65');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (66, 0, '66');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (67, 0, '67');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (68, 0, '68');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (69, 0, '69');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (70, 0, '70');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (71, 0, '71');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (72, 0, '72');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (73, 0, '73');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (74, 0, '74');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (75, 0, '75');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (76, 0, '76');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (77, 0, '77');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (78, 0, '78');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (79, 0, '79');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (80, 0, '80');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (81, 0, '81');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (82, 0, '82');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (83, 0, '83');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (84, 0, '84');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (85, 0, '85');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (86, 0, '86');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (87, 0, '87');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (88, 0, '88');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (89, 0, '89');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (90, 0, '90');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (91, 0, '91');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (92, 0, '92');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (93, 0, '93');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (94, 0, '94');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (95, 0, '95');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (96, 0, '96');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (97, 0, '97');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (98, 0, '98');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (99, 0, '99');
INSERT INTO APP.MEJA (ID, STATUS, NOMOR) 
	VALUES (100, 0, '100');

